package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProcesVerbalAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProcesVerbalAllPropertiesEquals(ProcesVerbal expected, ProcesVerbal actual) {
        assertProcesVerbalAutoGeneratedPropertiesEquals(expected, actual);
        assertProcesVerbalAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProcesVerbalAllUpdatablePropertiesEquals(ProcesVerbal expected, ProcesVerbal actual) {
        assertProcesVerbalUpdatableFieldsEquals(expected, actual);
        assertProcesVerbalUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProcesVerbalAutoGeneratedPropertiesEquals(ProcesVerbal expected, ProcesVerbal actual) {
        assertThat(expected)
            .as("Verify ProcesVerbal auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProcesVerbalUpdatableFieldsEquals(ProcesVerbal expected, ProcesVerbal actual) {
        assertThat(expected)
            .as("Verify ProcesVerbal relevant properties")
            .satisfies(e -> assertThat(e.getNumProcesV()).as("check numProcesV").isEqualTo(actual.getNumProcesV()))
            .satisfies(e -> assertThat(e.getResum()).as("check resum").isEqualTo(actual.getResum()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProcesVerbalUpdatableRelationshipsEquals(ProcesVerbal expected, ProcesVerbal actual) {}
}
